apiVersion: v1
kind: Service
metadata:
  name: catalog-config-service
  labels:
    app: catalog-config-service
spec:
  type: ClusterIP
  selector:
    app: catalog-config-service
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
